//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface HttpRequest : NSObject
{
}

+ (id)getTimeStamp;
+ (id)getSignWithDic:(id)arg1 interface:(id)arg2;
+ (id)getDicWithStr:(id)arg1;
+ (id)getJsonStrWithDic:(id)arg1;
+ (void)baseInterface:(id)arg1 postData:(id)arg2 callBack:(CDUnknownBlockType)arg3;
+ (void)getInterface:(id)arg1 callBack:(CDUnknownBlockType)arg2;
+ (void)postInterface:(id)arg1 postData:(id)arg2 callBack:(CDUnknownBlockType)arg3;

@end

