//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UIButton, UITextField;

@interface LoginViewController : UIViewController
{
    UITextField *_accountTf;
    UITextField *_pwdTf;
    UIButton *_loginBtn;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIButton *loginBtn; // @synthesize loginBtn=_loginBtn;
@property(nonatomic) __weak UITextField *pwdTf; // @synthesize pwdTf=_pwdTf;
@property(nonatomic) __weak UITextField *accountTf; // @synthesize accountTf=_accountTf;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)loginAction:(id)arg1;
- (void)viewDidLoad;

@end

